modelClass: Metadesignsolutions\Mdsoctoberseo\Models\Definition
defaultRedirect: metadesignsolutions/mdsoctoberseo/sitemap

form:
    fields:
        type:
            label: Type
            type: dropdown
            options: getTypeOptions
            default: 'defaultType'   
            hidden: true
        url:
            label: URL
            type: text
        reference:
            label: Reference
            type: dropdown
            options: getReferenceOptions
            default: 'defaultType'   
            hidden: true
        cmsPage:
            label: CMS Page
            type: dropdown
            options: getCmsPageOptions
            default: 'defaultType'   
            hidden: true
        changefreq:
            label: Change Frequency
            type: dropdown
            options:
                always: Always
                hourly: Hourly
                daily: Daily
                weekly: Weekly
                monthly: Monthly
                yearly: Yearly
                never: Never
            default: weekly
        priority:
            label: Priority
            type: number
            default: 0.5
            step: 0.1
            min: 0
            max: 1
        # nesting:
        #     label: Nesting
        #     type: number
        #     default: 1
        # allow_nesting:
        #     label: Allow Nested Items
        #     type: checkbox
        #     default: false
    toolbar:
        buttons: form_toolbar
        search: false
