import:
    modelClass: MetadesignSolutions\Mdsoctoberseo\Models\Redirect
    list: $/metadesignsolutions/mdsoctoberseo/models/redirect/columns.yaml
    redirect: metadesignsolutions/mdsoctoberseo/redirectmanager
    sessionKey: importExportSessionKey  # Ensure a session key is specified

export:
    modelClass: MetadesignSolutions\Mdsoctoberseo\Models\Redirect
    list: $/metadesignsolutions/mdsoctoberseo/models/redirect/columns.yaml
    redirect: metadesignsolutions/mdsoctoberseo/redirectmanager
    sessionKey: importExportSessionKey  # Ensure a session key is specified