modelClass: MetadesignSolutions\Mdsoctoberseo\Models\Redirect
defaultRedirect: metadesignsolutions/mdsoctoberseo/redirectmanager
form:
    fields:
        from_url:
            label: From URL
            type: text
            span: left
            tab: Redirect
            placeholder: '/example-path'
            comment: 'Enter the path to redirect from (e.g., /old-page)'

        to_url:
            label: To URL
            type: text
            span: right
            tab: Redirect
            placeholder: '/another-path'
            comment: 'Enter the destination path (e.g., /new-page)'

        status_code:
            label: Status Code
            type: dropdown
            options:
                301: '301 - Moved Permanently'
                302: '302 - Moved Temporarily'
                410: '410 - Gone'
            tab: General
            comment: 'Select the HTTP status code for the redirect'

        is_active:
            label: Active
            type: switch
            tab: General
            comment: 'Toggle to activate or deactivate the redirect'

    buttons:
        test_redirect:
            label: Test Redirect
            type: button
            cssClass: btn-secondary
            attributes:
                data-request: 'onTestRedirect'
                data-request-success: 'onTestRedirectSuccess'
            comment: 'Click to test the redirect functionality'
      