# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/metadesignsolutions/mdsoctoberseo/models/redirect/columns.yaml

# Model Class name
modelClass: MetadesignSolutions\Mdsoctoberseo\Models\Redirect

# List Title
title: Manage Redirects

# Link URL for each record
recordUrl: metadesignsolutions/mdsoctoberseo/redirectmanager/update/:id

# Message to display if the list is empty
noRecordsMessage: 'No redirects found. <br><small class="text-muted">SEO Toolkit by MetaDesign Solutions</small>'

# Records to display per page
recordsPerPage: 20

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: id
    direction: asc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
