modelClass: MetadesignSolutions\Mdsoctoberseo\Models\SeoSettings
defaultRedirect: metadesignsolutions/mdsoctoberseo/seo
noRecordsMessage: 'No SEO settings found. <br><small class="text-muted">SEO Toolkit by MetaDesign Solutions</small>'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: ~/plugins/metadesignsolutions/mdsoctoberseo/controllers/seo/_list_toolbar.php
    search:
        prompt: 'Search...'

list:
    columns:
        id:
            label: ID
            searchable: true
        name:
            label: Name
            searchable: true