modelClass: Metadesignsolutions\Mdsoctoberseo\Models\SeoSettings
defaultRedirect: metadesignsolutions/mdsoctoberseo/seo
noRecordsMessage: 'No records found'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: ~/plugins/metadesignsolutions/mdsoctoberseo/controllers/seo/_list_toolbar.php
    search:
        prompt: 'Search...'

list:
    columns:
        id:
            label: ID
            searchable: true
        name:
            label: Name
            searchable: true